# 基础镜像
FROM registry.cn-shanghai.aliyuncs.com/odboy/ops:runtime-jdk11
# 这里替换成你自己的应用名
ARG APP_NAME=#APP_NAME#
# 多环境情况下，是哪个环境（比如有日常daily、预发stage、生产online）
ARG APP_ENV=daily
# 以下内容不要动.
ENV APP_NAME=$APP_NAME
ENV APP_ENV=$APP_ENV
VOLUME /home/admin/$APP_NAME/logs/status
VOLUME /home/admin/$APP_NAME/logs/biz
VOLUME /home/admin/$APP_NAME/dumpfile
ADD ${APP_NAME}.tar.gz /home/admin/${APP_NAME}/